config/routes.rb
Rails.application.routes.draw do
  root 'works#index'
  resources :works
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/work.rb
class Work < ApplicationRecord
  validates :site_type, presence: true
  validates :url, presence: true
  validates :title, presence: true
  validates :detail, presence: true
  validates :is_finish, inclusion: { in: [true, false] }
  enum site_type: %i( crowdworks lancers)
  after_initialize :set_default, if: :new_record?

  def set_default
    self.site_type ||= :crowdworks
    self.is_finish ||= false
  end

  def is_finish?
    return expired_at < Date.today if expired_at.present?
    is_finish
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  def index
    @works = Work.all
  end

  def show
  end

  def new
    @work = Work.new
  end

  def edit
  end

  def create
    @work = Work.new(work_params)

    if @work.save
      redirect_to @work, notice: "#{Work.model_name.human}の作成に成功しました。"
    else
      render :new
    end
  end

  def update
    if @work.update(work_params)
      redirect_to @work, notice: "#{Work.model_name.human}の更新に成功しました。"
    else
      render :edit
    end
  end

  def destroy
    @work.destroy
    redirect_to works_path, notice: "#{Work.model_name.human}の削除に成功しました。"
  end

  private
    def set_work
      @work = Work.find(params[:id])
    end

    def work_params
      params.require(:work).permit(:site_type, :url, :title, :reward_min, :reward_max, :detail, :expired_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>案件管理 サンプル</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <main class="d-flex justify-content-center pt-5">
      <div class="col-10">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/works/_form.html.erb
<%= form_with(model: work, local: true) do |f| %>
  <% if work.errors.any? %>
    <div class="alert alert-danger alert-dismissible">
      <h2><%= work.errors.count %> つのエラーがあります。</h2>

      <ul>
      <% work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="form-group">
      <%= f.label :site_type %>
      <%= f.select :site_type, Work.site_types_i18n.invert, {}, class: "form-control" %>
    </div>


    <div class="form-group">
      <%= f.label :url %>
      <%= f.text_field :url, class: "form-control" %>
    </div>


    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>


    <div class="form-group">
      <%= f.label :reward_min %>
      <%= f.number_field :reward_min, class: "form-control" %>
    </div>


    <div class="form-group">
      <%= f.label :reward_max %>
      <%= f.number_field :reward_max, class: "form-control" %>
    </div>


    <div class="form-group">
      <%= f.label :detail %>
      <%= f.text_area :detail, class: "form-control" %>
    </div>
  <%= f.submit "送信", class: "btn btn-success" %>
<% end %>

app/views/works/edit.html.erb
<h1><%= Work.model_name.human %>編集</h1>

<%= render 'form', work: @work %>

<%= link_to '表示', @work, class: "btn btn-secondary" %>
<%= link_to '戻る', works_path, class: "btn btn-secondary" %>

app/views/works/index.html.erb
<h1><%= Work.model_name.human %>管理</h1>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= t Work.human_attribute_name(:site_type) %></th>
      <th><%= t Work.human_attribute_name(:title) %></th>
      <th><%= t Work.human_attribute_name(:reward_min) %></th>
      <th><%= t Work.human_attribute_name(:reward_max) %></th>
      <th><%= t Work.human_attribute_name(:status) %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.id %></td>


        <td><%= work.site_type_i18n %></td>



        <td><%= work.title.truncate(20) %></td>



        <td><%= work.reward_min %></td>



        <td><%= work.reward_max %></td>



        <td><%= work.is_finish? ? "終了" : "受付中" %></td>

        <td>
          <%= link_to '表示', work, class: "btn btn-secondary" %>
          <%= link_to '編集', edit_work_path(work), class: "btn btn-primary" %>
          <%= link_to '削除', work, method: :delete, class: "btn btn-danger", data: { confirm: '本当によろしいですか？' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規作成', new_work_path, class: "btn btn-success" %>

app/views/works/new.html.erb
<h1><%= Work.model_name.human %>新規作成</h1>

<%= render 'form', work: @work %>

<%= link_to '戻る', works_path, class: "btn btn-secondary" %>

app/views/works/show.html.erb
<h1><%= Work.model_name.human %>情報 表示</h1>


<table class="table table-striped">
  <tbody>
   <tr>
      <td><%= t Work.human_attribute_name(:site_type) %></td>

      <td><%= @work.site_type_i18n %></td>

    </tr>
   <tr>
      <td><%= t Work.human_attribute_name(:url) %></td>

      <td><%= link_to @work.url, @work.url, target: "_blank"%></td>

    </tr>
   <tr>
      <td><%= t Work.human_attribute_name(:title) %></td>

      <td><%= @work.title %></td>

    </tr>
   <tr>
      <td><%= t Work.human_attribute_name(:reward_min) %></td>

      <td><%= @work.reward_min %></td>

    </tr>
   <tr>
      <td><%= t Work.human_attribute_name(:reward_max) %></td>

      <td><%= @work.reward_max %></td>

    </tr>
   <tr>
      <td><%= t Work.human_attribute_name(:detail) %></td>

      <td><%= sanitize(simple_format(@work.detail.gsub(/\r\n|\r|\n/, "<br>")), tags: %w(br)) %></td>

    </tr>
   <tr>
      <td><%= t Work.human_attribute_name(:expired_at) %></td>

      <td><%= @work.expired_at %></td>

    </tr>
   <tr>
      <td><%= t Work.human_attribute_name(:status) %></td>

      <td><%= @work.is_finish? ? "終了" : "受付中" %></td>

    </tr>
   <tr>
      <td><%= t Work.human_attribute_name(:created_at) %></td>

      <td><%= l @work.created_at, format: :long %></td>

    </tr>
   <tr>
      <td><%= t Work.human_attribute_name(:updated_at) %></td>

      <td><%= l @work.updated_at, format: :long %></td>

    </tr>
  </tbody>
</table>

<%= link_to '編集', edit_work_path(@work), class: "btn btn-primary" %>
<%= link_to '戻る', works_path, class: "btn btn-secondary" %>